### ISSUE TITLE
Horizontal scroll bar in model detail view

### ISSUE THREAD

**Issue by clagom** [canonical/jaas-dashboard#423]
I'm sure it wasn't there before, it seems that the body width is causing a horizontal scroll bar in the page:

![Screenshot 2020-04-14 at 20.27.55.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/199dc96c-5496-4a8b-bfbf-2d440caf7b2e)

**Comment by hatched** [comment]
In order to reproduce this I had to change my setting from "when scrolling" to "always" or "automatic" (with a mouse hooked up)

![Screen Shot 2020-04-14 at 1 43 08 PM](https://user-images.githubusercontent.com/532033/79267249-17cfc100-7e56-11ea-98ae-8a7bb67240bd.png)

**Comment by barrymcgee** [comment]
In order to have responsive tables, they need to be set to overflow their contents once the screen resolution is less than the natural width of the table. This will result in a scroll bar. It can be hidden with CSS but that is an accessibility concern?

**Comment by huwshimi** [comment]
I can reproduce the case where the scrollbar appears when the table overflows (which appears to be by design), but I can't reproduce the full window scrollbars like the original screenshot.

<img width="1105" alt="Screen Shot 2022-09-19 at 1 41 56 pm" src="https://user-images.githubusercontent.com/361637/190946329-2f360a39-1a99-447f-a168-4a5f74fe13c9.png">

We can reopen this if someone is able to reproduce it.
