### ISSUE TITLE
Public address should be a link

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jaas-dashboard#725]
When exposing an application the next thing you are likely to want to do is visit the public address which we should make an easy accees link in the details. Which opens in a new tab.

**Comment by hatched** [comment]
There has been a lot of discussion over the years about allowing a charm to define it's addressable endpoints so that we could create links to them in the UI. So far nothing has materialized. People can also expose an application over a range of ports so we won't have just "one" link necessarily. It's also unlikely that the application gets exposed just on the IP and not on some additional path.

So this was a long way of saying we can definitely turn it into a link but it probably won't be super useful :)

**Comment by anthonydillon** [comment]
If we are displaying an IP, that is an address. Therefore seems reasonable to make it clickable instead making the user copy the text and entering it into another tab. Often the address is truncated and so the only way to reach the IP address is to inspect the table cell and copy the contents. 

We are not promising that the IP address will result in an application or the right place. That is an issue in which would be solved by charm authors providing ports and paths to there application UI. But, until then let's not make people inspect a page to get the address out of it, just to see.
